# Generated by Django 4.1.2 on 2022-10-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app112', '0003_alter_appeal_options_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyservice',
            options={'verbose_name': 'Экстренная служба', 'verbose_name_plural': 'Экстренные службы'},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('w', 'Женщина')], default='m', max_length=255, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='emergencyservice',
            name='service_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код службы'),
        ),
    ]
