# Generated by Django 4.1.1 on 2023-03-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app112', '0004_alter_emergencyservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='incidents',
            field=models.CharField(blank=True, choices=[('ДТП', 'ДТП'), ('Кража', 'Кража'), ('Нападение', 'Нападение'), ('Травма', 'Травма'), ('Пожар', 'Пожар'), ('Угроза терроризма', 'Угроза терроризма'), ('Другое', 'Другое')], default='Другое', max_length=255, verbose_name='Тип происшествия'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='appeals', to='app112.emergencyservice', verbose_name='Сервис'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='birthday',
            field=models.DateTimeField(blank=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('w', 'Женщина')], default=('m', 'Мужчина'), max_length=255, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, default='/', upload_to='photo/', verbose_name='Фотография'),
        ),
    ]
