# Generated by Django 4.1.1 on 2023-08-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app112', '0005_appeal_incidents_alter_appeal_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('In_work', 'В работе'), ('Completed', 'Завершено')], default='in work',
                                   max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина')], default=('Male', 'Мужчина'),
                                   max_length=255, verbose_name='Пол'),
        ),
    ]
