# Generated by Django 4.1.1 on 2023-12-18 11:40
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def swap_rus_incident_const_to_eng_for_appeals(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Appeal = apps.get_model('app112', 'Appeal')  # noqa
    rus_to_eng_incident = {
        'ДТП': 'Traffic_accident',
        'Кража': 'Theft',
        'Нападение': 'Attack',
        'Травма': 'Injury',
        'Пожар': 'Fire',
        'Угроза терроризма': 'Threat_of_terrorism',
        'Другое': 'Other',
    }

    for appeal in Appeal.objects.all():
        old_appeal_incident = appeal.incidents
        appeal.incidents = rus_to_eng_incident.get(old_appeal_incident, '')

        appeal.save(update_fields=['incidents'])


class Migration(migrations.Migration):

    dependencies = [
        ('app112', '0006_alter_appeal_status_alter_applicant_gender'),
    ]

    operations = [
    ]
