# Generated by Django 4.1.1 on 2023-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app112', '0007_auto_20231218_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='incidents',
            field=models.CharField(choices=[('Traffic_accident', 'ДТП (Дорожно-транспортное происшествие)'), ('Theft', 'Кража'), ('Attack', 'Нападение'), ('Injury', 'Травма'), ('Fire', 'Пожар'), ('Threat_of_terrorism', 'Угроза терроризма'), ('Other', 'Другое')], default='Other', max_length=255, verbose_name='Тип происшествия'),
        ),
    ]
