# Generated by Django 4.1.1 on 2023-12-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app112', '0009_alter_appeal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужчина'), ('Female', 'Женщина')], default='Male', max_length=255, verbose_name='Пол'),
        ),
    ]
