# Generated by Django 4.1.2 on 2022-10-26 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('birthday', models.DateTimeField(null=True, verbose_name='День рождения')),
                ('gender', models.CharField(choices=[('m', 'Мужчина'), ('w', 'Женщина')], max_length=255, null=True, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Фотография')),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('descr_state_health', models.TextField(blank=True, default='Практически здоров', help_text='Аллергоанамнез, хранические заболевания и т.д.', verbose_name='Описание состояния здоровья')),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Заявители',
                'ordering': ['surname', 'name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('service_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код службы')),
                ('phone', models.PositiveBigIntegerField(null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Экстренная служба',
                'verbose_name_plural': 'Экстренные службы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Номер обращения')),
                ('status', models.CharField(choices=[('in work', 'В работе'), ('completed', 'Завершено')], default='in work', max_length=255, verbose_name='Статус')),
                ('count_injured', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество пострадавших')),
                ('dontCall', models.BooleanField(default=True, verbose_name='Не звонить')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='app112.applicant', verbose_name='Заявитель')),
                ('service', models.ManyToManyField(blank=True, related_name='appeals', to='app112.emergencyservice', verbose_name='ID сервиса')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['date', 'number'],
            },
        ),
    ]
